stages:
  - deploy

deploy_to_github:
  stage: deploy
  script:
    - git config --global user.email "adrien.fauste-gay@univ-grenoble-alpes.fr"
    - git config --global user.name "GitLab Bot"
    
    # Clone GitLab Repository (Main Source)
    - git clone --mirror https://oauth2:$GITLAB_TOKEN@gitlab.com/faustega/grafs-e.git
    - cd grafs-e.git
    
    # Add GitHub as a remote
    - git remote add github https://oauth2:$GITHUB_TOKEN@github.com/AdrienFausteGay/GRAFS-E.git
    
    # Push everything to GitHub
    - git fetch --all
    - git push --mirror github
  only:
    - main  # or your default branch
