deploy_to_github:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519

    # ✅ Add GitHub & GitLab to known hosts
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

    # ✅ Use the correct SSH key
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_ed25519

    # ✅ Test connection
    - ssh -T git@gitlab.com

    # ✅ Clone the GitHub repository via SSH
    - git clone --mirror git@github.com:AdrienFausteGay/GRAFS-E.git github_repo
    - cd github_repo

    # ✅ Add GitLab as a remote
    - git remote add gitlab git@gitlab.com:faustega/grafs-e.git
    - git fetch gitlab --tags

    # ✅ Push everything to GitHub
    - git push --mirror origin
  only:
    - main
